Created url shortening application
fedora-infra/mote pull request #202
Opened 2021-10-27 19:58 UTC by tuba-mouqeem

Please review and suggest, how can I make it better?

2021-10-30 12:12 UTC, darknao commented
I'm not sure how to review this...
Can you explain what you have in mind? or provide a few examples on how to use this function?
I see a sqlite database, but you never use it to store anything. Did I miss something? Is this code working?

2021-11-01 09:55 UTC, Zlopez commented on src/mote/url_shortner.py
> +    def convereter_func(self, id):
```suggestion
    def converter_func(self, id):
```

2021-11-07 13:07 UTC, darknao requested changes
There are some good ideas here, but the implementation is far from complete.
Possible improvements are:
- Create 2 functions, one to convert a long url to a short one, and another to do the reverse (short to long url)
- The first function should check if the url already exist in db, and if not, create a new ShortUrl instance, generate the short url, save it into the db, then return the short url.
- The second one should query the db for the desired short url, and return the corresponding long one.
- Combine the 2 classes into one: move `converter_func` to the ShortUrl class, and rename it to something more meaningful like `get_short_url`. This function should use the object `id` (available as `self.id`)
- Create a route endpoint that take a short url in parameter, and redirect to the matching long url (something like `/<short_url>` or `/s/<short_url>`)

2021-12-08 04:16 UTC, t0xic0der commented
Closing this as stale

2021-12-08 04:16 UTC, closed without merging