Refactored hyperlinks in topbar
fedora-infra/mote pull request #207
Opened 2021-11-02 14:24 UTC by subhangi2731

Removed the `Channel` hyperlink from the top bar as suggested by @darknao in issue #206 and aligned the position of the `Get Fedora` hyperlink which is now perfectly in line with the `Fragment` logo.

@darknao @t0xic0der Please review

2021-11-03 18:35 UTC, darknao commented
Looks good, but other templates also need this alignment fix.

2021-11-03 18:47 UTC, subhangi2731 commented
All templates have been updated.

2021-11-04 18:40 UTC, darknao commented on src/mote/templates/statfile.html
> +                        <a style="color:#676767; text-decoration:none; margin-top: 4px;"
That's the wrong place.

2021-11-05 02:08 UTC, subhangi2731 commented on src/mote/templates/statfile.html
> +                        <a style="color:#676767; text-decoration:none; margin-top: 4px;"
Fixed the bug now.

2021-11-07 13:47 UTC, darknao approved these changes
Looks good.

2021-11-30 13:52 UTC, subhangi2731 commented
@t0xic0der this can be merged too?

2021-12-01 03:52 UTC, t0xic0der requested changes

2021-12-01 03:52 UTC, t0xic0der commented on src/mote/templates/e404page.html
> +                        <a class="text-white; margin-top: 4px;" href="https://getfedora.org/" target="_blank" type="button">Get Fedora</a>
```suggestion
                        <a class="text-white;" style="margin-top: 4px;" href="https://getfedora.org/" target="_blank" type="button">Get Fedora</a>
```

2021-12-01 03:53 UTC, t0xic0der requested changes
To https://github.com/fedora-infra/mote/pull/207#issuecomment-982656347, no.

2021-12-01 03:53 UTC, t0xic0der commented on src/mote/templates/e404page.html
> +                        <a class="text-white; margin-top: 4px;" href="https://getfedora.org/" target="_blank" type="button">Get Fedora</a>
```suggestion
                        <a class="text-white;" style="margin-top: 4px;" href="https://getfedora.org/" target="_blank" type="button">Get Fedora</a>
```

2021-12-01 07:29 UTC, subhangi2731 commented
@t0xic0der please check and let me know

2021-12-02 04:00 UTC, t0xic0der commented
I think that there's a change in direction for this pull request, after the review discussion that we had with @mairin in our weekly Websites and Apps Team meeting on 30th November 2021. The things that we need to do include - 

1. Removing the buttons from the center of the page
2. Placing them as link on the navbar - pretty much like how the `Channels` button was there

We can either make use of the same pull request or close this one to do stuff in a new one. Your call, @subhangi2731.

2021-12-02 09:36 UTC, subhangi2731 commented
@t0xic0der I was thinking maybe a new one will be better to make these new changes??

2021-12-04 05:13 UTC, subhangi2731 commented
@t0xic0der In reference to your comment you meant that the buttons `recent `, `explore` and `lookup`, I should remove from their original place(center) and keep it as link button in navbar like `channels` right? So as I have removed the `channels` hyperlink so in place of the `channels` hyperlink there will be these three buttons `recent`, `explore`, and `lookup` in place of that right with the same name right? Correct me please if I am wrong and then accordingly I will send a new pr

2021-12-06 05:45 UTC, t0xic0der commented
@subhangi2731, "all" buttons have to be removed from the center of the page and placed on the top-side as links on the navbar.

2021-12-06 06:24 UTC, subhangi2731 commented
@t0xic0der sure I will do this

2021-12-14 02:41 UTC, t0xic0der commented
I believe this can be closed in the wake of #230 being merged. Please feel free to reply back and reopen the PR if it's otherwise.

2021-12-14 02:41 UTC, closed without merging