Added footer in 404 page
fedora-infra/mote pull request #212
Opened 2021-11-03 14:22 UTC by subhangi2731

Closes #211 

Added footer in 404-error page.

2021-11-03 19:04 UTC, subhangi2731 commented
@darknao Can you share a screenshot of the footer being off the bottom? In my case, the 404 page footer is still at the very bottom of the page in all window sizes. 
Regarding the width, as you may notice, the 404 page's content takes up the whole page in comparison to meeting-details page where a box within the page shows the details and contains the footer.

2021-11-03 19:14 UTC, darknao commented
![image](https://user-images.githubusercontent.com/693402/140177183-b4b5756c-9c71-4d37-a81b-3941bb4a862c.png)

2021-11-04 02:54 UTC, subhangi2731 commented
In my case, the footer looks as usual
![Screenshot from 2021-11-04 08-23-08](https://user-images.githubusercontent.com/53938490/140250040-ad6cc2ee-31c8-44ae-a0a2-a486dd81ee7e.png)

2021-11-04 02:59 UTC, t0xic0der requested changes
Same for me, I guess.

![image](https://user-images.githubusercontent.com/49605954/140250460-a5cb92b4-0527-4f07-b9ba-9ea14912e0ac.png)

@subhangi2731, could you check if there's an inbuilt footer component packed in Bootstrap 5?

2021-11-04 03:51 UTC, subhangi2731 commented
@t0xic0der @darknao With the help of the in-built bootstrap I can add a footer in all the pages but this is a part of this issue #170. So if you can assign me that issue both will be covered under the same PR.
![Screenshot from 2021-11-04 08-51-38](https://user-images.githubusercontent.com/53938490/140255139-f3d1f268-5725-4411-bf59-b48731cbaff9.png)

2021-11-10 17:41 UTC, subhangi2731 commented
@darknao I have updated the changes please review

2021-11-10 18:00 UTC, subhangi2731 commented
@t0xic0der @darknao please review my updated PR

2021-11-23 20:12 UTC, darknao commented
This is still not working.
Check this bootstrap example for reference : https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/
Note that you need to use flexbox to make it work like that.

But there is several way to solve this issue.
If you look at others pages, you'll notice the footer is actually a card footer.
Why not just use this same logic here, and move everything in a card, like in the main page?

2021-11-25 17:56 UTC, subhangi2731 commented
@darknao okay I will do this and update the PR

2021-11-29 08:04 UTC, t0xic0der requested changes
Why the long padding at the top?

![image](https://user-images.githubusercontent.com/49605954/143829970-6f374ca0-091d-4045-b36e-fea6b7c4047d.png)

2021-11-29 08:17 UTC, subhangi2731 commented
@t0xic0der sorry will correct the padding other than this is everything okay?

2021-11-30 02:21 UTC, t0xic0der commented
@subhangi2731, I'd suggest that you correct the padding first and then maybe, I'll give it another round of review to see if there's anything else that needs changing.

2021-11-30 10:21 UTC, subhangi2731 commented
@t0xic0der sure

2021-12-01 03:36 UTC, t0xic0der approved these changes
LGTM.

Merging.

2021-12-01 03:37 UTC, t0xic0der requested changes
Please ignore https://github.com/fedora-infra/mote/pull/212#pullrequestreview-819774086. Changes are still needed.

2021-12-01 14:43 UTC, subhangi2731 commented
@t0xic0der @darknao I corrected the long padding, kept all the contents in the card component, and then also brought the footer in correct alignment and now it's totally down touching the end of the page. Please check and let me know

2021-12-01 14:44 UTC, subhangi2731 commented
![Screenshot from 2021-12-01 20-01-35](https://user-images.githubusercontent.com/53938490/144255131-5c6bbd52-cb88-4ed6-834a-7ef47c8096ca.png)

2021-12-01 14:46 UTC, subhangi2731 commented
![footer alignment](https://user-images.githubusercontent.com/53938490/144255520-017f3991-7627-42a6-a567-ea1db21ca42f.png)

2021-12-01 14:51 UTC, subhangi2731 commented
![Screenshot from 2021-12-01 20-21-09](https://user-images.githubusercontent.com/53938490/144256517-6c604e05-8dd5-4a62-91c9-d153e48c8889.png)

2021-12-01 14:53 UTC, subhangi2731 commented
![Screenshot from 2021-12-01 20-23-03](https://user-images.githubusercontent.com/53938490/144256851-85de5084-60d2-4ac6-bfbb-e41bf1a8ccd8.png)

2021-12-01 15:28 UTC, darknao commented on src/mote/templates/e404page.html
> +                    <img src="{{ url_for('static', filename='imgs/404_not_found.svg') }}" style="width: 40%; height: 40%;" />
It works fine on Chrome, but have some extra padding at the bottom on Firefox.
One way to fix that is by removing the height css attribute on the 404 image (which is not really needed anyway):
```suggestion
                    <img src="{{ url_for('static', filename='imgs/404_not_found.svg') }}" style="width: 40%;" />
```

2021-12-01 15:42 UTC, subhangi2731 commented
@darknao sure

2021-12-01 15:48 UTC, subhangi2731 commented
@darknao please check and let me know

2021-12-01 15:54 UTC, darknao approved these changes
:+1:

2021-12-02 03:52 UTC, t0xic0der approved these changes
Made one small change to bring the card segment to the center of the page.

2021-12-02 03:52 UTC, merged

2021-12-02 04:50 UTC, subhangi2731 commented
@t0xic0der great