Remove the buttons and add as links in navbar
fedora-infra/mote pull request #230
Opened 2021-12-08 17:16 UTC by subhangi2731

Removed the buttons from the center of the page and placed them as links in the navbar. Also removed the logo and placed it in the navbar. All the contents from the body of the main page are also removed as the calendar has to be integrated and set up with the search meeting logs bar for the recent meetings

Closes #221

2021-12-08 17:17 UTC, subhangi2731 commented
@darknao @t0xic0der please have a look here and let me know

2021-12-08 19:43 UTC, darknao commented on src/mote/templates/mainpage.html
> -        <script src="{{ url_for('static', filename='jscn/socket.io.js') }}"></script>
This line should not be removed.

2021-12-08 19:46 UTC, darknao requested changes
`imgs/Fedora_logo.png` is missing

2021-12-09 04:09 UTC, subhangi2731 commented
@darknao please check now

2021-12-09 13:30 UTC, darknao approved these changes
Looks good to me :+1:

2021-12-14 02:32 UTC, merged